[bar.main]
background_opacity = 0.0
capsule = true
capsule_opacity = 0.5
compositor_blur = false
shadow = false
border_width = 0.0
smart_auto_hide = true
reserve_space = false

[nightlight]
enabled = true
force = false
temperature_day = 6500
temperature_night = 4500

[location]
custom_schedule = true
sunset = "21:30"
sunrise = "06:30"
